# C/C++ with GCC

# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
    CC: gcc-7
    CXX: g++-7
    
steps:
- task: CmdLine@2
  inputs:
    script: |
      mkdir build_debug
      cd build_debug
      cmake -DCMAKE_BUILD_TYPE=DEBUG -DLIEN_BUILD_TESTS_BENCHMARKS=OFF ..
      cmake --build .
      cd ..

- task: CmdLine@2
  inputs:
    script: |
      cd build_debug/output/bin/lien_tests
      ./lien_base_tests -r junit -o lien_base_tests.xml
      ./lien_image_tests -r junit -o lien_image_tests.xml
      ./lien_parallel_tests -r junit -o lien_parallel_tests.xml
      ./lien_strutils_tests -r junit -o lien_strutils_tests.xml
      
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'build_debug/output/bin/lien_tests/*.xml'