#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
# INIT SCRIPT
#+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

# -- C++ STANDARD WITHOUT EXTENSIONS --
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# -- COMPILER --
IF (CMAKE_CXX_COMPILER_ID MATCHES "/CLANG/i")
    SET(LIEN_COMPILER_CLANG TRUE)
ENDIF()

IF (CMAKE_CXX_COMPILER_ID MATCHES "/MSVC/i")
    SET(LIEN_COMPILER_MSVC TRUE)
ENDIF()

IF (CMAKE_CXX_COMPILER_ID MATCHES "/GNU/i")
    SET(LIEN_COMPILER_GCC TRUE)
ENDIF()

IF (CMAKE_CXX_COMPILER_ID MATCHES "/INTEL/i")
    SET(LIEN_COMPILER_INTEL TRUE)
ENDIF()

# -- ARCH --
if (CMAKE_SYSTEM_PROCESSOR MATCHES "(x86)|(X86)|(amd64)|(AMD64)")
    set (LIEN_ARCH_X86 TRUE)
endif ()

if (CMAKE_SYSTEM_PROCESSOR MATCHES "arm|ARM|aarch64|AARCH64")
    set (LIEN_ARCH_ARM TRUE)
endif ()

# -- UTILS --
macro(LIEN_SET_SHARED_LIB_OUTPUT_DIR DIR)
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY 			${DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG 	${DIR})
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE 	${DIR})
endmacro()

macro(LIEN_SET_STATIC_LIB_OUTPUT_DIR DIR)
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY 			${DIR})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG 	${DIR})
    set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE 	${DIR})
endmacro()

macro(LIEN_SET_EXECUTABLE_OUTPUT_DIR DIR)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY 			${DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG 	${DIR})
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE 	${DIR})
endmacro()